# Generated by Django 6.0.2 on 2026-02-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LampioneManutenzione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arm_id', models.IntegerField(db_index=True)),
                ('arm_data_ini', models.DateField(blank=True, null=True)),
                ('arm_data_fin', models.DateField(blank=True, null=True)),
                ('arm_altezza', models.FloatField(blank=True, null=True)),
                ('arm_lunghezza_sbraccio', models.FloatField(blank=True, null=True)),
                ('arm_numero_lampade', models.IntegerField(blank=True, null=True)),
                ('arm_lmp_potenza_nominale', models.FloatField(blank=True, null=True)),
                ('tar_cod', models.CharField(blank=True, max_length=50, null=True)),
                ('tar_descr', models.CharField(blank=True, max_length=255, null=True)),
                ('tmo_id', models.FloatField(blank=True, null=True)),
                ('tpo_cod', models.CharField(blank=True, max_length=50, null=True)),
                ('tpo_descr', models.CharField(blank=True, max_length=255, null=True)),
                ('sgn_id', models.FloatField(blank=True, null=True)),
                ('sgn_data_inserimento', models.DateTimeField(blank=True, null=True)),
                ('tcs_id', models.FloatField(blank=True, null=True)),
                ('tcs_descr', models.CharField(blank=True, max_length=255, null=True)),
                ('tci_id', models.FloatField(blank=True, null=True)),
                ('tci_descr', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LampioneNuovo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arm_id', models.IntegerField(db_index=True)),
                ('arm_data_ini', models.DateField(blank=True, null=True)),
                ('arm_data_fin', models.DateField(blank=True, null=True)),
                ('arm_altezza', models.FloatField(blank=True, null=True)),
                ('arm_lunghezza_sbraccio', models.FloatField(blank=True, null=True)),
                ('arm_numero_lampade', models.IntegerField(blank=True, null=True)),
                ('arm_lmp_potenza_nominale', models.FloatField(blank=True, null=True)),
                ('tar_cod', models.CharField(blank=True, max_length=50, null=True)),
                ('tar_descr', models.CharField(blank=True, max_length=255, null=True)),
                ('tmo_id', models.FloatField(blank=True, null=True)),
                ('tpo_cod', models.CharField(blank=True, max_length=50, null=True)),
                ('tpo_descr', models.CharField(blank=True, max_length=255, null=True)),
                ('sgn_id', models.FloatField(blank=True, null=True)),
                ('sgn_data_inserimento', models.DateTimeField(blank=True, null=True)),
                ('tcs_id', models.FloatField(blank=True, null=True)),
                ('tcs_descr', models.CharField(blank=True, max_length=255, null=True)),
                ('tci_id', models.FloatField(blank=True, null=True)),
                ('tci_descr', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
