# Generated by Django 6.0.2 on 2026-02-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lampione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arm_id', models.IntegerField(db_index=True, unique=True)),
                ('arm_data_ini', models.DateField(blank=True, null=True)),
                ('arm_data_fin', models.DateField(blank=True, null=True)),
                ('arm_altezza', models.FloatField(default=0.0)),
                ('arm_lunghezza_sbraccio', models.FloatField(default=0.0)),
                ('arm_numero_lampade', models.IntegerField(default=0)),
                ('arm_lmp_potenza_nominale', models.FloatField(default=0.0)),
                ('tar_descr', models.CharField(blank=True, max_length=255, null=True)),
                ('tpo_descr', models.CharField(blank=True, max_length=255, null=True)),
                ('sgn_data_inserimento', models.DateTimeField(blank=True, null=True)),
                ('tcs_descr', models.CharField(blank=True, max_length=255, null=True)),
                ('tci_descr', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
