# Generated by Django 6.0.2 on 2026-02-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lampionenuovo',
            name='latitudine',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lampionenuovo',
            name='longitudine',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
