# Generated by Django 6.0.2 on 2026-02-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lampionenuovo_latitudine_lampionenuovo_longitudine'),
    ]

    operations = [
        migrations.AddField(
            model_name='lampionemanutenzione',
            name='latitudine',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lampionemanutenzione',
            name='longitudine',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
