# Generated by Django 6.0.2 on 2026-02-19 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_lampionemanutenzione_latitudine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lampionemanutenzione',
            name='giorni_guasto',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
