# Generated by Django 6.0.2 on 2026-02-19 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_lampionemanutenzione_giorni_guasto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lampionemanutenzione',
            name='giorni_guasto',
        ),
    ]
