# Generated by Django 6.0.2 on 2026-02-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_lampionemanutenzione_giorni_guasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='lampionemanutenzione',
            name='risk_score',
            field=models.FloatField(blank=True, help_text='Probabilità di guasto (da 0.0 a 1.0)', null=True),
        ),
        migrations.AddField(
            model_name='lampionemanutenzione',
            name='risk_score_date',
            field=models.DateTimeField(blank=True, help_text="Data dell'ultimo calcolo ML", null=True),
        ),
    ]
