# Generated by Django 6.0.2 on 2026-02-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_lampionemanutenzione_risk_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lampionenuovo',
            name='risk_score',
            field=models.FloatField(blank=True, help_text='Probabilità di guasto (0.0-1.0)', null=True),
        ),
        migrations.AddField(
            model_name='lampionenuovo',
            name='risk_score_date',
            field=models.DateTimeField(blank=True, help_text='Data calcolo AI', null=True),
        ),
        migrations.AlterField(
            model_name='lampionemanutenzione',
            name='risk_score',
            field=models.FloatField(blank=True, help_text='Probabilità di guasto (0.0-1.0)', null=True),
        ),
        migrations.AlterField(
            model_name='lampionemanutenzione',
            name='risk_score_date',
            field=models.DateTimeField(blank=True, help_text='Data calcolo AI', null=True),
        ),
    ]
