# Generated by Django 6.0.2 on 2026-02-19 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_lampionenuovo_risk_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lampionemanutenzione',
            name='risk_score',
        ),
        migrations.RemoveField(
            model_name='lampionemanutenzione',
            name='risk_score_date',
        ),
    ]
