# Generated by Django 6.0.2 on 2026-02-19 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_lampionenuovo_giorni_rottura'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lampionenuovo',
            old_name='giorni_rottura',
            new_name='traQuantoSiRompe',
        ),
    ]
