# Generated by Django 6.0.2 on 2026-02-20 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_giorni_rottura_lampionenuovo_traquantosirompe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lampionenuovo',
            name='risk_score',
        ),
        migrations.RemoveField(
            model_name='lampionenuovo',
            name='risk_score_date',
        ),
        migrations.AddField(
            model_name='lampionenuovo',
            name='giorni_vita_attuale',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lampionenuovo',
            name='prob_guassto',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
