# Generated by Django 6.0.2 on 2026-02-20 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_lampionenuovo_risk_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lampionenuovo',
            old_name='prob_guassto',
            new_name='prob_guasto',
        ),
    ]
