# Generated by Django 6.0.2 on 2026-02-20 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_prob_guassto_lampionenuovo_prob_guasto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lampionenuovo',
            old_name='prob_guasto',
            new_name='risk_score',
        ),
    ]
