# Generated by Django 6.0.2 on 2026-02-20 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_prob_guasto_lampionenuovo_risk_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='lampionenuovo',
            name='risk_score_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
