# Generated by Django 6.0.2 on 2026-02-20 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_lampionenuovo_risk_score_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lampionenuovo',
            name='risk_score_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
