# Generated by Django 6.0.2 on 2026-02-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_lampionenuovo_risk_score_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segnalazioni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arm_id', models.IntegerField(db_index=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('problema', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
