# Generated by Django 6.0.2 on 2026-02-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_segnalazioni'),
    ]

    operations = [
        migrations.AddField(
            model_name='segnalazioni',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
